name: Linux/Windows Build
run-name: ${{ github.actor }} is building splatapult
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install System Packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: libxmu-dev libxi-dev libgl-dev libxcb-glx0-dev libglu1-mesa-dev libxxf86vm-dev libxrandr-dev
      - name: Project Build
        run: |
            chmod +x build.sh
            ./build.sh linux
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get Microsoft Visual Studio for C++
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install CMake
        uses: lukka/get-cmake@v3.29.0
      - name: Create Build Dir
        run: mkdir build
      - name: CMake Configure
        working-directory: build
        run: cmake -DSHIPPING=ON -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
      - name: CMake Build
        working-directory: build
        run: cmake --build . --config=Release
      - name: Upload Artifiacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/Release